### ISSUE TITLE
Drag an drop of .bib file into JabRef leads to exception

### ISSUE THREAD

**Issue by koppor** [InAnYan/jabref#73]
![grafik](https://github.com/InAnYan/jabref/assets/1366654/6b917064-686e-4160-9c7a-5ff1e0c711a6)

**Comment by koppor** [comment]
```
java.lang.RuntimeException: java.util.NoSuchElementException
	at org.jabref@100.0.0/org.jabref.logic.ai.embeddings.EmbeddingsGenerationTask.lambda$configure$0(EmbeddingsGenerationTask.java:75)
	at org.jabref@100.0.0/org.jabref.gui.util.UiTaskExecutor.lambda$getJavaFXTask$5(UiTaskExecutor.java:186)
	at javafx.base@22.0.1/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
	at javafx.base@22.0.1/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:232)
	at javafx.base@22.0.1/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:189)
	at javafx.base@22.0.1/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at javafx.base@22.0.1/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base@22.0.1/com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at javafx.base@22.0.1/com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
	at javafx.base@22.0.1/javafx.event.Event.fireEvent(Event.java:198)
	at javafx.graphics@22.0.1/javafx.concurrent.EventHelper.fireEvent(EventHelper.java:219)
	at javafx.graphics@22.0.1/javafx.concurrent.Task.fireEvent(Task.java:1332)
	at javafx.graphics@22.0.1/javafx.concurrent.Task.setState(Task.java:709)
	at javafx.graphics@22.0.1/javafx.concurrent.Task$TaskCallable.lambda$call$2(Task.java:1429)
	at javafx.graphics@22.0.1/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:456)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at javafx.graphics@22.0.1/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:455)
	at javafx.graphics@22.0.1/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at javafx.graphics@22.0.1/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at javafx.graphics@22.0.1/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:184)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.util.NoSuchElementException
	at java.base/java.util.List.removeLast(List.java:881)
	at org.jabref@100.0.0/org.jabref.logic.ai.embeddings.EmbeddingsGenerationTask.call(EmbeddingsGenerationTask.java:157)
	at org.jabref@100.0.0/org.jabref.logic.ai.embeddings.EmbeddingsGenerationTask.call(EmbeddingsGenerationTask.java:37)
	at org.jabref@100.0.0/org.jabref.gui.util.UiTaskExecutor$1.call(UiTaskExecutor.java:173)
	at javafx.graphics@22.0.1/javafx.concurrent.Task$TaskCallable.call(Task.java:1399)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
```

**Comment by InAnYan** [comment]
@koppor the issue shouldn't be on current `ai-pr-1` branch.

Could you redo this? Or maybe provide "how to reproduce"?

Did you drag-n-dropped `Chocolate.bib` and all?

**Comment by InAnYan** [comment]
AH

So when you drag-n-drop a `.bib` file in JabRef it inserts entries in currently opened tab?

**Comment by InAnYan** [comment]
The issue seems not present, so waiting from your side

**Comment by koppor** [comment]
The screenshots were misleading. One can drag and drop a BibTeX file (file extension: .bib) to the tab bar in JabRef to **open** the bib file.

I checked with the latest version. Works.
